## Generated by dust2 (version 0.3.16) - do not edit
transmission_model <- structure(
  function() get("transmission_model"),
  class = "dust_system_generator",
  name = "transmission_model",
  package = "PREVAIL",
  path = NULL,
  parameters = data.frame(
    name = c("n_age", "n_vacc", "n_risk", "S0", "I0", "Rpop0", "incubation_rate", "recovery_rate", "cfr_normal", "natural_immunity_waning", "prop_severe", "severe_recovery_rate", "cfr_severe", "prop_complications", "R0", "tt_R0", "no_R0_changes", "contact_matrix", "seeded", "tt_seeded", "no_seeded_changes", "crude_death", "no_death_changes", "tt_death_changes", "simp_birth_death", "crude_birth", "no_birth_changes", "tt_birth_changes", "repro_low", "repro_high", "age_maternal_protection_ends", "protection_weight_vacc", "protection_weight_rec", "aging_rate", "tt_vaccination_coverage", "no_vacc_changes", "vaccination_coverage", "age_vaccination_beta_modifier", "no_migration_changes", "tt_migration", "migration_in_number", "migration_distribution_values", "short_term_waning", "long_term_waning"),
    type = c("int", "int", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "int", "real_type", "int", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "real_type", "int", "real_type", "real_type", "int", "real_type", "real_type", "real_type", "real_type", "real_type"),
    constant = c(TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, TRUE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, TRUE, FALSE, FALSE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE),
    required = c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE),
    rank = c(0L, 0L, 0L, 3L, 3L, 3L, 0L, 0L, 1L, 0L, 3L, 0L, 1L, 1L, 1L, 1L, 0L, 2L, 4L, 1L, 0L, 3L, 0L, 1L, 0L, 2L, 0L, 1L, 0L, 0L, 0L, 0L, 0L, 1L, 1L, 0L, 4L, 3L, 0L, 1L, 4L, 2L, 1L, 1L)),
  properties = list(
    time_type = "discrete",
    has_compare = FALSE,
    has_adjoint = FALSE),
  default_dt = 1)
